### ISSUE TITLE
"output is too small" error

### ISSUE THREAD

**Issue by halmos** [crepererum-oss/tatutanatata#228]
I'm running into the following error when I attemp to export a mailbox: 

```
Error: execute command

Caused by:
    0: download mail (`https://app.tuta.com/mail/LyVjKB5--7-2/MFhFrOZ----2`)
    1: decode body
    2: decompress
    3: decompression
    4: provided output is too small for the decompressed data, actual 17442, expected 17451
```

The process halts before exporting the remaining emails. Even if one email fails, it would be great to proceed with the export.

**Comment by crepererum** [comment]
Could you use the provided link in your browser and check if you can manually export there?

**Comment by crepererum** [comment]
Looking at the error message, this seems like a bizarre bug. Are you sure you're using the latest code from this repository?

**Comment by crepererum** [comment]
Could you try the code from #230 and tell me if that panics?

**Comment by halmos** [comment]
Thanks, I tied the #230 issue branch and am no longer receiving the compression error. However, the export has no stalled-out after reporting the following: 
```
2024-07-17T14:10:22.397901Z  INFO tatutanatata: download folder_id="LyVjKB5--7-2" mail_id="O0GEs-5--3-9" target_file=../exports/qadune-2/2024-06-25-21h13m54s-ICE Dispenser  Week of June 24 2024.eml ui_url="https://app.tuta.com/mail/LyVjKB5--7-2/O0GEs-5--3-9"
2024-07-17T14:10:22.446721Z  WARN tatutanatata::file_output: retry rename e=No such file or directory (os error 2)
2024-07-17T14:10:22.676721Z  INFO tatutanatata: download folder_id="LyVjKB5--7-2" mail_id="O0GEsIt----9" target_file=../exports/qadune-2/2024-06-25-21h13m55s-ICE Dispenser  Week of June 24 2024.eml ui_url="https://app.tuta.com/mail/LyVjKB5--7-2/O0GEsIt----9"
2024-07-17T14:12:00.883438Z  WARN tatutanatata::file_output: retry rename e=No such file or directory (os error 2)
2024-07-17T14:20:03.556092Z  WARN tatutanatata::file_output: retry rename e=No such file or directory (os error 2)
```

**Comment by crepererum** [comment]
May I ask you what kind of filesystem your are exporting too? I've seen similar issues on some network mounts.

**Comment by halmos** [comment]
I'm running OS X 14.3. The disk is just the internal drive (no network mount or anything like that).

**Comment by crepererum** [comment]
#231 should fix the retry behavior.

**Comment by halmos** [comment]
Thanks, no more problems with the previous errors. I am seeing some errors that look like this now tho:
``` 
2024-07-18T21:26:06.786007Z  WARN tatutanatata::client: retry client error e=HTTP status client error (429 Too Many Requests) for url (https://app.tuta.com/rest/storage/blobaccesstokenservice)
```

It seems like Tuta may have API throttling and the request needs a retry with backoff? Or is this a side-effect of #231?

**Comment by halmos** [comment]
Also - just got this new error:
```
Error: execute command

Caused by:
    0: download mail: `https://app.tuta.com/mail/LyUY5na--F-2/NK4EWIa----9`
    1: get file infos
    2: deserialize JSON for `alloc::vec::Vec<tatutanatata::proto::messages::FileReponse>`
    3: [0]._ownerEncSessionKey: invalid type: null, expected a string at line 1 column 116
```

Sounds like the code might need to catch errors due to poorly formed json...

**Comment by crepererum** [comment]
This happens if you don't run the app to receive all the emails from the inbound queue. We could improve the error message, but I don't plan to implement the crypto to deal with this case.

**Comment by crepererum** [comment]
> It seems like Tuta may have API throttling and the request needs a retry with backoff?

That's expected because we don't know the rate limit of the server, so we hit it until it tells us to back off. You could lower the concurrency, but it's also not really an issue.

**Comment by halmos** [comment]
> This happens if you don't run the official app to receive all the emails from the inbound queue. We could improve the error message, but I don't plan to implement the crypto to deal with this case.

To clarify, does this mean that the error is thrown if the official app has not already retrieved the email from the queue?

**Comment by crepererum** [comment]
> > This happens if you don't run the official app to receive all the emails from the inbound queue. We could improve the error message, but I don't plan to implement the crypto to deal with this case.
> 
> To clarify, does this mean that the error is thrown if the official app has not already retrieved the email from the queue?

correct.

We could potentially make the error a bit nicer though.

**Comment by halmos** [comment]
> We could potentially make the error a bit nicer though.

Would it be possible to catch the error so that the export process didn't halt when the error is encountered?

**Comment by crepererum** [comment]
Sure, if someone wants to file a PR 🙂

**Comment by halmos** [comment]
> Sure, if someone wants to file a PR 🙂
I definitely would if I knew anything about Rust! Sorry to not be of much help here.

I'm seeing a new error now: 
```
Error: execute command

Caused by:
    0: list mail
    1: fetch next page
    2: deserialize JSON for `alloc::vec::Vec<tatutanatata::proto::messages::MailReponse>`
    3: [664].mailDetails: invalid type: null, expected an array of length 2 at line 1 column 1048634
 ```

**Comment by crepererum** [comment]
@halmos I've extracted the two open problems into separate issues so we can track them easier. I'll close this issue here. Please open NEW issues for separate issues.
