### ISSUE TITLE
`MailReponse::mailDetails` element is null?

### ISSUE THREAD

**Issue by crepererum** [crepererum-oss/tatutanatata#258]
I'm seeing a new error now: 
```
Error: execute command

Caused by:
    0: list mail
    1: fetch next page
    2: deserialize JSON for `alloc::vec::Vec<tatutanatata::proto::messages::MailReponse>`
    3: [664].mailDetails: invalid type: null, expected an array of length 2 at line 1 column 1048634
 ```

_Originally posted by @halmos in https://github.com/crepererum-oss/tatutanatata/issues/228#issuecomment-2297150142_

**Comment by Azusa37** [comment]
I am also seeing the same error after #278 is fixed.
It happens not long after the download continued from the previous error, so probably it is also related to old mail format.

**Comment by crepererum** [comment]
Could someone that faces this issue try the same debugging approach as in #273
? i.e.

- use the debug PR #274
- either share the dumped JSON here or send it via email to the mail address mentioned on this web page https://crepererum.net/pages/about/ 
- safety note: the JSON contains no real plain text data or keys that someone could use, just a bit of meta data and you would trust me (or this issue tracker) the same way as you trust Tuta. If you see any string in there that you wanna strip, just replace it with `"???"` while preserving the JSON structure.

**Comment by Azusa37** [comment]
I have sent a json file to you email.

I had a quick look at the dumped file. It seems the error happens when it hits an email sent from a tuta address to a non-tuta address, and in that case the `mailDetails` field is `null`.

**Comment by crepererum** [comment]
Got the mail, will have a look at it when I get the time (hopefully not far in the future).
