### ISSUE TITLE
Error deserializing: trailing characters

### ISSUE THREAD

**Issue by tcm5343** [crepererum-oss/tatutanatata#273]
Attempting to export a folder to a given path and I get the following error. I'm running the latest changes from the master branch. When I re-run, it keeps returning the same error. I only have been able to export 520 emails thus far. Any idea what might be causing this?

```
> cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
```

```
Error: execute command

Caused by:
    0: download mail: `https://app.tuta.com/mail/*****`
    1: get file infos
    2: deserialize JSON for `alloc::vec::Vec<tatutanatata::proto::messages::FileReponse>`
    3: [0].blobs: trailing characters at line 1 column 678
```

**Comment by crepererum** [comment]
Could you try to build the binary from this PR here: https://github.com/crepererum-oss/tatutanatata/pull/274 and post the JSON that it spits out to the terminal somewhere? This may leak some private information though (it's technically all encrypted, but IIRC sender/receiver mail addresses are in clear text), if that's an issue but you trust me enough (so it's at least not public), you can send it via email to the address that you find on this page here: https://crepererum.net/pages/about/ (using some indirection to make it a bit harder for spam bots).

**Comment by crepererum** [comment]
My suspicion is that the JSON that the server sends back is somewhat fishy/malformed.

**Comment by crepererum** [comment]
I should also note that while the JSON might leak some metadata, it shouldn't leak the mail content. Sending me this doesn't leak the encryption keys. It's basically the data that the provider stores. So you would trust me as a debugger as much as you trust Tuta.

**Comment by tcm5343** [comment]
Email sent, thanks.

**Comment by crepererum** [comment]
That helped, thanks. The error message is somewhat misleading (or at least not helpful). The JSON is perfectly valid, it's just that our code assumes that all files have exactly one data blob. However it seems that large files are split into multiple data blobs. I have to dig a bit further to understand the exact semantics of is (e.g. is base64 encoding and encryption done before or after concatenating the blobs). Should be a rather easy fix though.
