### ISSUE TITLE
Error "encrypted blobs do not add up to file size"

### ISSUE THREAD

**Issue by Azusa37** [crepererum-oss/tatutanatata#278]
Hi, I was trying to downloading a folder using the command in `Readme` and ran into this error:

```
Error: execute command

Caused by:
    0: download mail: `https://app.tuta.com/mail/LZRFBMQ-17-1/LZjPlka----1`
    1: download file #1
    2: encrypted blobs do not add up to file size, should be 78692 bytes but got 78753 bytes
```

I think it is trying to download a pdf attachment.

Also something I'm not sure is related or not: if I open the link in browser, I'll get redirected to login page and the inbox. The folder id is actually `LZRFBMQ-1--1` in browser, but in the program it's `LZRFBMQ-17-1`.

**Comment by crepererum** [comment]
What size does the PDF attachment have if you store it as a file?

I'm wondering if I misunderstood that size field 🤔

**Comment by Azusa37** [comment]
I just retried it again and I realized I made a typo yesterday. Actually because the program is running multi-threaded, there are two failures happening with the same error: one is a `png` file, one is a `pdf` file.

The `png` file give the error mentioned above:
```
2: encrypted blobs do not add up to file size, should be 78692 bytes but got 78753 bytes
```

and the `pdf` file gives
```
    0: download mail: `https://app.tuta.com/mail/LZRFBMQ-17-1/LZss_IK----1`
    1: download file #1
    2: encrypted blobs do not add up to file size, should be 37863 bytes but got 37921 bytes
```

I checked the file sizes (I downloaded the files directly with browser) with `ls -l` on Linux. The `png` file is `78692` long and the `pdf` file is `37863` long, so it seems the field itself is right, but the downloaded blobs have some extra data?

I cannot share the files because they contains private info, but I'll try to see if I can find a filed attachment I can share.

**Comment by crepererum** [comment]
So I thought that the field that we get from the server does not describe the actual data size of the final file, but the size if the encrypted data (which has a few extra bytes). At least that was the case for the tests that I ran. Maybe they changed it at some point? Can you roughly tell me when you received that email (like maybe the year and the month, just to roughly if that's recent data or not).

**Comment by Azusa37** [comment]
The two emails are from Feb-Mar of 2019, they are quite old.

**Comment by crepererum** [comment]
That's somewhat in line my hypothesis that they've changed that at some point, and hence cannot replicate that now. I'll downgrade that hard assertion to a warning.

**Comment by crepererum** [comment]
> Also something I'm not sure is related or not: if I open the link in browser, I'll get redirected to login page and the inbox. The folder id is actually `LZRFBMQ-1--1` in browser, but in the program it's `LZRFBMQ-17-1`.

I'ts unrelated, but still a bug which will confuse people. So I've extracted this into #279. Thanks for reporting!
