### ISSUE TITLE
Webdriver Execution Error

### ISSUE THREAD

**Issue by bobasipping** [crepererum-oss/tatutanatata#44]
Hello! Thank you for creating such a useful tool! I have been having a hard time with the slow searches in Tutanota, and this would really make my day easier! Unfortunately, I have minimal background in code, and could barely get tatutanatata to login in without the .env because I could not figure out how to make the credentials to load. Running cargo after inserting the .env to the tatutanatata root did not seem to solve it. But more importantly, I kept on receiving the following while trying to export, and sometimes something similar when I try to list the folders too - my chances of getting the list-folders command to work is significantly higher when the Tutanota desktop app is not running in parallel, but that it no guarantee, and I still have not gotten the export command to work as of yet. I am running Tatutanatata in MacOS if the context helps. Could you please help me troubleshoot the issue?

"Error: webdriver execution

Caused by:
    0: export
    1: navigate to folder
    2: list folders
    3: list of folders should never be empty"

**Comment by crepererum** [comment]
It's currently broken because Tutanota changed their UI and someone has to sit down and fix it. Also see #34.

**Comment by christianweinz** [comment]
I'm also running into errors. I'm unfortunately not skilled enough to solve this.
```
$ cargo run --release -- --username $email --password $pw list-folders
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/tatutanatata --username ***** --password ***** list-folders`
Error: webdriver execution

Caused by:
    0: perform login
    1: find login button
    2: not found
```
