### ISSUE TITLE
suggestion for README

### ISSUE THREAD

**Issue by eriteric** [crepererum-oss/tatutanatata#8]
Hi, thanks for making this! Great name.

I had to have tutanota open in another browser during the process to confirm/authorize the login from the CLI, might be good to mention that. The message in gecko when that happens is this: 
```
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofilecwPgJx/search.json.mozlz4", (void 0)))
console.warn: LoginRecipes: "Falling back to a synchronous message for: https://mail.tutanota.com."
```

**Comment by eriteric** [comment]
Oh, then yes. Do you have to confirm the new login in a browser too?

**Comment by crepererum** [comment]
No, you don't have to. The browser is "remote controlled" / puppeteered via a protocol called WebDriver. So the code virtually clicks through the headless (i.e. w/o any real GUI) browser. There are currently some limitations regarding 2FA though, see #10.
