### ISSUE TITLE
Not able to export because of pay more screen

### ISSUE THREAD

**Issue by eriteric** [crepererum-oss/tatutanatata#9]
For accounts nearing their storage limit there is a pay more lightbox that pops up and this stops the export process. Below are the details for it:

lightbox container id: "modal"
close button class: "limit-width noselect bg-transparent button-height"

error output:
```
2023-01-15T16:55:48.251309Z  INFO tatutanatata::commands::export: folder still loading
2023-01-15T16:55:49.267229Z  INFO tatutanatata::commands::export: found mail list list_size=41 list_height=6868
2023-01-15T16:55:49.315604Z  INFO tatutanatata::commands::export: handle entry list_size=41 y=0
Error: webdriver execution

Caused by:
    0: export
    1: click at list element
    2: webDriver command error: webdriver returned error: Element <li class="list-row pl pr-l odd-row"> is not clickable at point (471,104) because another element <div class="b"> obscures it
```

**Comment by crepererum** [comment]
That's pretty hard to debug / fix for me since this doesn't happen for my account and blindly design the right detection and click sequence sounds like a pretty wasteful activity.

Any chance that you could forge a PR for that?

**Comment by eriteric** [comment]
Sure, understandable. I can give it a shot. I haven't ever used rust but what I'm reading in the code makes sense.
